### ISSUE TITLE
[New]EMU-150 흰색

### ISSUE THREAD

**Issue by JukjeonWani** [MEGB-NewGRF/KoreanTrainSet_Plus#10]
**그래픽 스프라이트(Graphic sprite):**

![EMU150_WHITE](https://user-images.githubusercontent.com/88026704/173176272-506c1f3e-31db-4e6b-8f4a-7526a13a59ec.png)

**제안할 차량 제원(Suggest vehicle specification):**
EMU-150 도색개조로 추가

**Comment by GBLINER** [comment]
코딩완료
