### ISSUE TITLE
[New]EMU-150 2층객차

### ISSUE THREAD

**Issue by JukjeonWani** [MEGB-NewGRF/KoreanTrainSet_Plus#11]
**그래픽 스프라이트(Graphic sprite):**

빨강(기본)
![EMU150_RED-DUP](https://user-images.githubusercontent.com/88026704/173176391-c63ce52d-04c1-4d5e-a129-a91e5b80cf79.png)
녹색
![EMU150_GREEN-DUP](https://user-images.githubusercontent.com/88026704/173176394-96f0a4bf-66b3-4796-8c52-4c1deabd0773.png)
흰색
![EMU150_WHITE-DUP](https://user-images.githubusercontent.com/88026704/173176399-108b7b5a-4a35-49c4-84fd-58311b9ecc07.png)

**제안할 차량 제원(Suggest vehicle specification):**
| Property | Suggest value |
|--------|--------|
| 이름(Name in Korean) _(예시. ``KTX 산천``)_ | 2층객차 |
| 영문 이름(Name in English) _(예시. ``KTX Sancheon``)_ | Duplex Car |
| 화물 수송량(Capacity) _(예시. ``100명``)_ | 98(1층 48명, 2층 50명) |
| 중량(Weight) _(예시. ``136t``)_ | 25t |
| 도입연도(Introduction year) _(예시. ``2004``)_ | 2023 |

EMU-150 공통객차로 편성 후 개조를 통해 만들 수 있는 객차입니다. 풀 2층규격의 열차는 TC칸을 포함한 스프라이트를 다른 디자인으로 만들어서 ITX-새마을 DD의 도색개조로 편입할 예정입니다. 이 차량은 EMU-150에 귀속된 객차로 만드시면 됩니다. 도색도 EMU-150 도색을 따릅니다

**Comment by evepoi** [comment]
2층형 일반실 객차, 운전차량이 추가되면 도입될 예정입니다.
