### ISSUE TITLE
[New]에코레일 관광열차(신도색)

### ISSUE THREAD

**Issue by JukjeonWani** [MEGB-NewGRF/KoreanTrainSet_Plus#16]
**그래픽 스프라이트(Graphic sprite):**
![ECORAIL_passinger](https://user-images.githubusercontent.com/88026704/181564298-73044db2-d87a-44de-9ed9-66b508c1052f.png)

**제안할 차량 제원(Suggest vehicle specification):**
| Property | Suggest value |
|--------|--------|
| 이름(Name in Korean) _(예시. ``KTX 산천``)_ | 관광열차 객차 |
| 영문 이름(Name in English) _(예시. ``KTX Sancheon``)_ | Travel cargo |
| 코드(Code) _(예시. ``KTX2N``)_ | ``eco_pas`` |
| 운영 속력(Speed) _(예시. ``300km/h``)_ | 150 km/h |
| 설계 최고 속력(Designed max. speed) _(예시. ``330km/h``)_ | 150 km/h |
| 화물 수송량(Capacity) _(예시. ``100명``)_ | 64명 |
| 출력(Power) _(예시. ``4400kW``)_ | none |
| 중량(Weight) _(예시. ``136t``)_ | 20t |
| 도입연도(Introduction year) _(예시. ``2004``)_ | 2010 |

**그래픽 스프라이트(Graphic sprite):**
![ECORAIL_bike](https://user-images.githubusercontent.com/88026704/181730332-e6eeff1a-d6ef-45a1-ac35-7ae835f6e3d6.png)

**제안할 차량 제원(Suggest vehicle specification):**
| Property | Suggest value |
|--------|--------|
| 이름(Name in Korean) _(예시. ``KTX 산천``)_ | 관광열차 수화물차 |
| 영문 이름(Name in English) _(예시. ``KTX Sancheon``)_ | Travel post |
| 코드(Code) _(예시. ``KTX2N``)_ | ``eco_bike`` |
| 운영 속력(Speed) _(예시. ``300km/h``)_ | 150 km/h |
| 설계 최고 속력(Designed max. speed) _(예시. ``330km/h``)_ | 150 km/h |
| 화물 수송량(Capacity) _(예시. ``100명``)_ | 우편 50t |
| 출력(Power) _(예시. ``4400kW``)_ | none |
| 중량(Weight) _(예시. ``136t``)_ | 17t |
| 도입연도(Introduction year) _(예시. ``2004``)_ | 2010 |

ref.
https://youtu.be/fo_-gmKvvTE (수화물차 한쪽 통로부 색이 측면 색과 다른 이유는 해당 영상을 확인 후 의도한 사항입니다)
https://blog.naver.com/gray8501/222658890973
https://blog.naver.com/daniel4409/222739157235

에코레일 차량의 경우 2010년경부터 운행을 시작한 것으로 보입니다. 해당 스프라이트는 신도색이지만 구도색 스프라이트도 언젠간 만들어질것이기때문에 2010년 등장으로 했습니다. 차량 이름의 경우도 향후 다른차량 추가 시 도색개조로 추가할 수 있도록 하기 위해 미리 대비한 명칭입니다.

에코레일의 경우 전용기관차와 발전차가 없습니다. 지금은 GT26CW에 연결 후 한국열차세트의 발전차를 연결하면 됩니다. 그렇다고 발전차를 안만드는것은 아닙니다. 전용발전차가 있는 경우도 있기에 이 경우를 대비해 스프라이트를 하나 만들어둘 생각이지만 그 때까지 열차 추가를 미룰 필요가 없다는 의미입니다.

**Comment by opentrain** [comment]
이열차 자료같은경우는 구도색도 제가 반영해보겠습니다.

**Comment by JukjeonWani** [comment]
@opentrain 구도색은 수화물차만 작업하면 될 겁니다. 찾아보니까 초기도색, 구도색 두종류 있더군요.
전용객차는 신도색(현재도색) 바뀌면서 추가된거라 구도색 차량은 한열셋 객차에 조합해서 써도 됩니다.
