### ISSUE TITLE
[New]충북영동국악와인열차

### ISSUE THREAD

**Issue by JukjeonWani** [MEGB-NewGRF/KoreanTrainSet_Plus#18]
**그래픽 스프라이트(Graphic sprite):**
![wine_desel](https://user-images.githubusercontent.com/88026704/181730984-f4aa494c-25b6-4db5-b808-11f824f67812.png)

**제안할 차량 제원(Suggest vehicle specification):**
GT26CW 도색개조(성능 변동 없음)

**그래픽 스프라이트(Graphic sprite):**
![wine_passinger](https://user-images.githubusercontent.com/88026704/181731072-1386aa82-4112-458b-be55-843e6c6fb16f.png)

**제안할 차량 제원(Suggest vehicle specification):**

* ``관광열차 객차`` 에서 개조

| Property | Suggest value |
|--------|--------|
| 이름(Name in Korean) _(예시. ``KTX 산천``)_ | 충북영동국악와인열차 |
| 영문 이름(Name in English) _(예시. ``KTX Sancheon``)_ | Chungbuk Yeongdong Gugak & Wine Train |
| 코드(Code) _(예시. ``KTX2N``)_ | ``CY_G&W`` |
| 운영 속력(Speed) _(예시. ``300km/h``)_ | 150 km/h |
| 설계 최고 속력(Designed max. speed) _(예시. ``330km/h``)_ | 150 km/h |
| 화물 수송량(Capacity) _(예시. ``100명``)_ | 1호차, 2호차, 4호차~6호차: 72명, 3호차: 68명 |
| 출력(Power) _(예시. ``4400kW``)_ | 0 |
| 중량(Weight) _(예시. ``136t``)_ | 20t |
| 도입연도(Introduction year) _(예시. ``2004``)_ | 2006 |

**그래픽 스프라이트(Graphic sprite):**
![wine_bike](https://user-images.githubusercontent.com/88026704/181731798-5539e703-c751-49e7-9192-4d53d14527b8.png)

**제안할 차량 제원(Suggest vehicle specification):**
``관광열차 수화물차``에서 개조(성능 변동 없음)

등장년도는 이 열차의 전신인 와인트레인을 기준으로 했습니다 이전의 차량들을 새마을호 개조형 차량이기에 승차정원이 64명임을 감안해주시기 바라며, 해당 차량은 무궁화호 객차이기때문에 방송실, 휠체어석이 설치된 3호차만 정원 68명, 나머지 객차는 정원 72명으로 설정하였습니다.
수화물차의 경우 에코레일 자전거열차처럼 자전거를 싣고 다니는 것으로 보입니다.도색을 보니 외부에 자전거 그림과 "eco"글자가 적혀있는 것을 확인하였습니다.

**전체 편성 조합**
![국악와인](https://user-images.githubusercontent.com/88026704/181733471-fededfb3-9a5a-42f9-a612-4d91dbc18991.png)

ref
https://blog.naver.com/tmxoavm6913/221309675935
https://blog.naver.com/insoo9348/221222667106
https://blog.naver.com/tntjrlwl/221174790523
https://blog.naver.com/skyliner1025/221931135814
https://blog.naver.com/railroad0501/222788625253
https://blog.naver.com/daniel4409/222794403082
https://youtu.be/pL4jYaX4Urc

**Comment by opentrain** [comment]
해당 이 이슈에서 영동국악와인열차가 되기전 와인인삼트레인하고 와인시네마트레인도 여기에 넣어도될까요?

**Comment by JukjeonWani** [comment]
@opentrain 두 차량은 수송정원이 64명이므로 별도 이슈로 올리는 것을 추천드립니다
