### ISSUE TITLE
[New] 한국철도공사 8500호대 전기기관차

### ISSUE THREAD

**Issue by Gamunbi** [MEGB-NewGRF/KoreanTrainSet_Plus#20]
**그래픽 스프라이트(Graphic sprite):**
![전기기관차 8x00호대, 8500호대 1차 완성 KTS+](https://user-images.githubusercontent.com/75788864/181937220-e30649db-099b-4d2c-84b4-c68bbbdac27c.png)

**제안할 차량 제원(Suggest vehicle specification):**
| Property | Suggested name |
|--------|--------|
| 이름(Name in Korean) | 한국철도공사 8500호대 전기기관차 |
| 영문 이름(Name in English)  | KORAIL Class 8500 Electric Locomotive |
| 코드(Code) | ``K8500`` |
| 운영 속력(Speed) | 150 km/h |
| 설계 최고 속력(Designed max. speed)  | 165 km/h |
| 출력(Power)  | 6600 kW |
| 중량(Weight)  | 132 t |
| 도입연도(Introduction year)  | 2012 |

https://namu.wiki/w/8500%ED%98%B8%EB%8C%80%20%EC%A0%84%EA%B8%B0%EA%B8%B0%EA%B4%80%EC%B0%A8

----

스프라이트 조정 방법
1. 우선 모두 공통 객차와 동일하게 합니다.
2. y좌표를 2px씩 아래로 내립니다.

----
아래 자료는 다른 도색을 만들 때 참고하세요.

↓기본 형태
![001](https://user-images.githubusercontent.com/75788864/181938496-2718a53c-b445-4d99-bd1d-42386357e9d4.png)
↓도색이 바뀌어도 바뀌지 않는 필수요소인 대차, 전조등, 창문, 환풍구, 팬터그래프 등 첨부(로고는 바뀔 수 있음)
![002](https://user-images.githubusercontent.com/75788864/181938510-011dcbbc-3b94-475c-ad91-d9cc2702f31f.png)

**Comment by evepoi** [comment]
한국열차세트에 있는 차량이므로, 관광열차 도색으로 추가된 이슈 위주로 등록하겠습니다.
