### ISSUE TITLE
[New]8500호대 관광열차 도색

### ISSUE THREAD

**Issue by JukjeonWani** [MEGB-NewGRF/KoreanTrainSet_Plus#21]
**그래픽 스프라이트(Graphic sprite):**
![FEL8500_tour](https://user-images.githubusercontent.com/88026704/182028721-0d35b09a-6358-4c55-bddf-16ea9909ca96.png)

**제안할 차량 제원(Suggest vehicle specification):**
8500호대 전기기관차에서 개조

* 해당 차량은 게임을 플레이하는 유저 대부분이 전기선로 등장 이후 비전철 선로보다는 전철화 선로를 주로 사용한다는 점과 최근 탄소중립의 일환으로 관광열차와 임시화물열차(갑종회송)등을 전기기관차로 진행한 사례에 착안하여 작업한 스프라이트입니다. 
* A-train, G-train, S-train, V-train, 해랑 다섯가지의 도색은 한국열차세트의 관광열차 객차와 짝을 이뤄 운행하는 것을 의도한 도색입니다. 또한, 충북영동국악와인열차 도색은 KTS+에 추가예정인 관광열차, 충북영동국악와인열차와 짝을 이룰 차량으로 KTS+에 넣는걸 추천합니다.
*  한열셋 관광열차는 고정편성이므로 디젤기관차가 연결된 차량 앞이나 뒤에 연결하여 운행하는것을 전제로 했습니다. JGR패치팩을 사용하는 경우 비전철화 선로도 운행 가능하면서(이 경우 전기기관차는 끌려가는 무동력차가 됨) 전기선로에서 성능을 극대화 시킬 목적(디젤기관차와 전기기관차 모두 작동)으로 사용하는 차량이 될 수 있습니다

**의도한 편성 예시**
![image](https://user-images.githubusercontent.com/88026704/182029467-0fd3c04c-a8e7-46b0-855b-d350a435c0e9.png)

**Comment by evepoi** [comment]
스프라이트 규격 맞지 않으로 보류.

**Comment by evepoi** [comment]
보류하려 했으나, 새로운 템플릿으로 적용합니다.
