### ISSUE TITLE
[New] NRT2 신도색

### ISSUE THREAD

**Issue by JukjeonWani** [MEGB-NewGRF/KoreanTrainSet_Plus#25]
**그래픽 스프라이트(Graphic sprite):**
* 파랑
![NRT2_B new](https://user-images.githubusercontent.com/88026704/182603694-581bcdac-db7b-4d7d-a09b-84508dfdbd94.png)
* 초록
![NRT2_G new](https://user-images.githubusercontent.com/88026704/182603715-689a5be7-7e07-4508-9c34-736eb80b330f.png)
* 하양
![NRT2_W new](https://user-images.githubusercontent.com/88026704/182603728-22e9b95c-1083-4b66-b9f1-914ad650cefb.png)

**제안할 차량 제원(Suggest vehicle specification):**
NRT2 도색개조로 추가

https://blog.naver.com/dalsungbam123/222838715118
![image](https://user-images.githubusercontent.com/88026704/182603915-1baac537-4e7c-4654-8f67-d76a0a72b44a.png)
누리로 신도색이 등장함에 따라 누리로 2층차량인 NRT2 신도색을 작업해봤습니다.

**Comment by evepoi** [comment]
흰색도색은 기존 NRT2와 차이 없으므로, 추가하지 않겠습니다.

**Comment by JukjeonWani** [comment]
@evepoi 작업 안할까 하다가 희미하게 푸른빛 선 보이길래 같이 작업해둔거에요. 아주 사소한거지만..

**Comment by evepoi** [comment]
추가하신 3가지 도색 모두 적용했습니다.
