### ISSUE TITLE
[열차변경] 레이디버드

### ISSUE THREAD

**Issue by Gamunbi** [MEGB-NewGRF/KoreanTrainSet_Plus#39]
==========[필수스프라이트]==========
![관광 레이디버드 1차 완성](https://user-images.githubusercontent.com/75788864/183411281-5d661d62-f31d-4a01-a8c1-a728a67287e9.png)

==========[설명]==========
레이디버드 스프라이트 수정

발전차도 KTS 플러스 기본 규격에 맞게 고쳤습니다. 스프라이트 조정은 발전차 포함 전부 동일하게 하시면 됩니다. 이 발전차의 길이는 6입니다.

==========[KTS+적용내용]==========
적용될 기존 열차 이름 : 레이디버드

**Comment by opentrain** [comment]
감사합니다.^^ 레이디버드로 통해서 e-train도 새로 다시 수정하겠습니다.

**Comment by JukjeonWani** [comment]
![Ladybird](https://user-images.githubusercontent.com/88026704/184523639-275358f8-d14b-4006-b224-fdee010a0c5d.png)
ref.
* https://blog.naver.com/kimsngher/150009732360
* https://blog.naver.com/kimchoonsig/221564858885

**수정사항**
* 1호차 →방향과 9호차 ←방향의 길이를 객차와 맞췄습니다, (전망차의 연결통로막 부분은 채우지 않고 비워둠)
* 9호차 냉방장치의 방향을 다른 객차와 통일시켰습니다(래퍼런스 참고)
