### ISSUE TITLE
[New] CTX

### ISSUE THREAD

**Issue by EightonEight** [MEGB-NewGRF/KoreanTrainSet_Plus#46]
from [MEGB-NewGRF/VirtualTrainSet#21](https://github.com/MEGB-NewGRF/VirtualTrainSet/issues/21)

#### 그래픽 스프라이트(Graphic sprite):
![CTX_FC_R](https://user-images.githubusercontent.com/77984422/192987026-96c92aec-7116-4081-a358-76f305673d67.png)
`CTX_FC_R` (Freight Car)

![CTX_HC_R](https://user-images.githubusercontent.com/77984422/192987498-efad4ea7-8302-47a6-bb6d-1427f0bfec63.png)
`CTX_HC_R` (passenger/freight Hybrid Car)

#### 제안할 차량 제원(Suggest vehicle specification):
| Property | Suggest value |
|--------|--------|
| 이름 | CTX / CTX |
| 코드 | `CTX` |
| 운영 속력 | 300 km/h |
| 설계 최고 속력 | 330 km/h |
| 화물 수송량 | 화물 20t/량(개조 가능) |
| 출력 | 8800kW |
| 중량 | 136t |
| 도입연도 | 2020 |

도색 이름: 
* CTX 화물전용 와인도색  /  CTX Freight Only Wine Livery
* CTX 여객-화물복합 와인도색 / CTX Passenger-Freight Wine Livery

최소 편성수 : 기관차 포함 4량
편성 조성 방법 :
```
4량: PC1 - T1 - T4 - PC2 
5량: PC1 - T1 - T2 - T4 - PC2 
6량: PC1 - T1 - T2 - T3 - T4 - PC2 
7량~: PC1 - T1 - T2 - ⋯ -  T2 - T3 - ⋯ - T3 - T4 - PC2 
```

과거 연구되었던 CTX(Cargo Train eXpress, 고속화물열차)와 Hy-SoBex(Hybrid-Surface optimal Baggage express, 여객/화물 고속복합열차)입니다.

실제 수송량은 15t 정도이나, 게임상 편의를 위해 20t으로 설정하였습니다.

OpenTTD 게임 특성 상 한 차량에 승객과 화물을 동시에 실을 수 없으므로, 스프라이트 상으로만 여객/화물 복합열차를 구현하고  게임 내에서는 화물만 싣게 하면 좋을 것 같습니다.
(ex: T1, T4 또는 PC1, PC2를 화물만 싣게 설정)

#### References:
* 고속화물열차 제원
  - 한국철도기술연구원, 「차량편성구성에 따른 고속화물열차의 추진 및 제동성능 분석 연구」, 2016
* 여객/화물 고속복합열차 제원
  - 한국철도공사, 「여객/화물 고속복합열차를 이용한 소화물 운송 최적 서비스 모델 연구」, 2014
* 도색 디자인 참고
  - 한국철도공사, 「고속차량 KTX-산천 디자인의미 소개」, 2012

**Comment by evepoi** [comment]
화물 : 최종 운반하는 상품, 최종 생산물등으로 화물을 설정하겠습니다.
