### ISSUE TITLE
[열차변경] HSR-350X에 동력거점식 설정 추가

### ISSUE THREAD

**Issue by EightonEight** [MEGB-NewGRF/KoreanTrainSet_Plus#51]
#### ==========[필수스프라이트]==========
`HSR_350X` 스프라이트를 그대로 사용

#### ==========[설명]==========
현재 게임 내에서 처음 열차 구매 시 열차 조성은 다음과 같으며, 실제 7량 시험편성과 동일합니다.
```
PC1 - TM1 - TT2 - TT3 - ⋯ - TT3 - TT4 - ⋯ - TT4 - TM5 - PC2
```
그러나 스프라이트를 제작 할 당시 의도한 바와 달리, TM5 객차를 이용한 동력거점식 열차 구현이 불가능한 상태입니다.

따라서 열차를 처음 구매할 때 TM5 차량이 나오게 하지 않고, 도색변경 기능을 이용해 TT3, TT4, TM1 차량을 TM5 차량 스프라이트로 변경하여 동력거점식 열차 및 시험편성을 구현하면 좋을 것 같습니다.
```
처음 구매 시 - PC1 - TM1 - TT2 - TT3 - ⋯ - TT3 - TT4 - ⋯ - TT4 - TM1 - PC2
도색 변경 시 - PC1 - TM1 - TT2 - TT3 - ⋯ - TM5 - TM5 - ⋯ - TT4 - TM5 - PC2
```

Ex:
![image](https://user-images.githubusercontent.com/77984422/193445837-eeedbff0-d57a-443d-8eff-ca133e5d6d02.png)

#### ==========[KTS+적용내용]==========
적용될 기존 열차 이름 : `HSR_350X`

**Comment by evepoi** [comment]
도색변경을 동력분산식 & 동력거점식의 두가지의 개조방식으로만 선택하도록 할 예정입니다.
- 동력분산식 선택시 : 제안 (처음 열차 구매시)
- 동력거점식 선택시 : 제안 (일부 차량 도색 변경시)
로 자동 편성되도록하여 이용자가 일일이 별도 선택하지 않도록 설정할 예정.

기본 10량 단편성의 기준과 10량 중련 구성일때의 구성에 맞출 예정이므로, 기타 편성시에는 필요한 편성이 나오지 않을 수 있음을 사전에 인지 드립니다.

**Comment by EightonEight** [comment]
> 우선 동력집중식의 편성에 맞추어 적용해두겠습니다.

기술적인 문제로 적용이 되지 않는다면 TM5를 없애지 않고 현 코드 그대로 유지하면 좋을 것 같습니다.

**Comment by evepoi** [comment]
> 기술적인 문제로 적용이 되지 않는다면 TM5를 없애지 않고 현 코드 그대로 유지하면 좋을 것 같습니다.

동력 집중식으로 거론해주신 편성방식으로 적용했습니다.
