### ISSUE TITLE
[열차변경] EMU260, EMU320 계열 스프라이트 개선 및 추가

### ISSUE THREAD

**Issue by EightonEight** [MEGB-NewGRF/KoreanTrainSet_Plus#53]
### EMU260
![EMU260_W](https://user-images.githubusercontent.com/77984422/198955758-4f0a77d8-8e8f-479c-b64e-94c52fceabad.png)
변경: `EMU260` → `EMU260_W`

![EMU260_BK](https://user-images.githubusercontent.com/77984422/198955774-4b4e6a91-33dd-4a28-9579-97a3e1777c4e.png)
추가: `EMU260_BK`

![EMU260_250](https://user-images.githubusercontent.com/77984422/198955780-1f8ae204-d519-4790-b77a-d7166c87deb7.png)
추가: `EMU260_250`

### EMU320
![EMU320_CC](https://user-images.githubusercontent.com/77984422/198955832-db18d5c8-68df-4b11-9dd6-99909abe289e.png)
변경: `EMU320` → `EMU320_CC`

![EMU320_BK](https://user-images.githubusercontent.com/77984422/198955881-d73f9bcc-f255-4086-9b20-161586b23969.png)
추가: `EMU320_BK`

![EMU320_SRT](https://user-images.githubusercontent.com/77984422/198955922-08fb3d2b-9e1d-4281-9fab-9a9c3a5ac5b7.png)
변경: `EMU320_SRT`

![EMU320_SRT2](https://user-images.githubusercontent.com/77984422/198955999-f01c544a-b748-4898-8f3d-19ee16309551.png)
(추가: `EMU320_SRT2`)

### KTX_EM
![EMU260_DD](https://user-images.githubusercontent.com/77984422/199022181-c26c71ba-3948-4dc9-8cfd-116de0b48e1f.png)
변경: `KTX_EM` → `EMU260_DD`

### KTX_N
![EMU320_DD (2)](https://user-images.githubusercontent.com/77984422/199022217-3f2746a9-b56d-4d17-a2b0-50bc5921a8e0.png)
변경: `KTX_N` → `EMU320_DD`

#### ==========[32bpp스프라이트]==========
![EMU260_DD_32bpp](https://user-images.githubusercontent.com/77984422/199022202-bf2c2f42-acc8-41c1-ad69-a905414a5e80.png)
추가: `KTX_EM_32bpp` (`EMU260_DD_32bpp`)

#### ==========[설명]==========
과거 차량 디자인 시안, 모형 등을 참고하여 스프라이트를 개선하였습니다.
`EMU320_SRT2`는 기존 SRT320 도색 디자인을 임의로 개선한 것이며, 레퍼런스는 없으므로 따로 추가를 하지 않으셔도 됩니다.

코드명 변경이 어렵다면 그대로 두고 스프라이트만 변경하면 될 것 같습니다.

**References:**
* EMU260
  - <https://www.cctoday.co.kr/news/articleView.html?idxno=1003164>
  - <https://intersect.dcmys.kr/198>
  - <https://blog.naver.com/digmon2001/220395456516>
* EMU320, KTX_N
  - <https://www.chosun.com/site/data/html_dir/2016/11/28/2016112802076.html>
  - <https://blog.naver.com/trainking311000/221563530785>
  - <http://www.businesskorea.co.kr/news/articleView.html?idxno=16463>

#### ==========[KTS+적용내용]==========
적용될 기존 열차 이름 : EMU-260, EMU-320, KTX-이음 DD, EMU-320 DD
도색 추가시 열차 이름 : 
* EMU-260
  - EMU-260 흰색도색 / EMU-260 White Livery
  - EMU-260 검정도색 / EMU-260 Black Livery
  - HEMU-250 초기도색 / HEMU-250 Prototype Livery
* EMU-320
  - EMU-320 회사색상 / EMU-320 Company Colour
  - EMU-320 검정도색 / EMU-320 Black Livery
  - EMU-320 SRT / EMU-320 SRT
  - (EMU-320 SRT2 / EMU-320 SRT2)
* KTX_EM, KTX_N
  - 현행 유지

편성 조성 방법:
* EMU-260, KTX_EM
```
4량: TC1 - M1 - M3 - TC2 
5량: TC1 - M1 - M2 - M3 - TC2 
6량: TC1 - M1 - M2 - M2 - M3 - TC2 
7량~: TC1 - M1 - M2 - ⋯ -  M2 - M3 - TC2 
```
* EMU-320
```
4량: TC1 - M1 - M4 - TC2 
5량: TC1 - M1 - M2 - M4 - TC2 
6량: TC1 - M1 - M2 - M3 - M4 - TC2 
7량: TC1 - M1 - M2 - M3 - M2 - M4 - TC2 
8량: TC1 - M1 - M2 - M3 - M2 - M2 - M4 - TC2 
9량: TC1 - M1 - M2 - M3 - M2 - M2 - M3 - M4 - TC2 
10량~: TC1 - M1 - M2 - M3 - M2 - M2 - M3 - M2 - M4 - TC2 (M3가 4호차부터 3칸씩 반복)
```
* KTX-N
```
4량: PC1 - T1 - T2 - PC2 
5량: PC1 - T1 - T1 - T2 - PC2 
6량: PC1 - T1 - T1 - T2 - T2 - PC2 
7량~: PC1 - T1  - ⋯ - T1 - T2 - ⋯ - T2 - PC2  
```

**Comment by evepoi** [comment]
제공해주신 편성과 스프라이트는 가능함 전부 적용되도록 해보겠습니다.
